### ISSUE TITLE
Delay between FinishedLoadingURL and actually playing the sound

### ISSUE THREAD

**Issue by dan-lee** [johnsonsu/react-native-sound-player#59]
I want to show a bar of the current progress of playing my file from a URL:

```js
const listener = SoundPlayer.addEventListener(
  'FinishedLoadingURL',
  async result => {
    const info = await SoundPlayer.getInfo()

    Animated.timing(playingAnimationValue.current, {
      toValue: 100,
      duration: info.duration * 1000
    }).start()
  }
)
```

Unfortunately there's a delay between `FinishedLoadingURL` and the file actually being played. How can I resolve this without having an artificial delay?
Thanks!

edit: Seems to be more a problem on iOS than Android

**Comment by johnsonsu** [comment]
Hi @dan-lee, I just published version `0.10.0` which might fix your issue, please give it a try!

**Comment by dan-lee** [comment]
Hey @johnsonsu sorry for the delay and thanks for addressing it.
I suppose the way to do it now is: 
```
SoundPlayer.loadUrl(url)
SoundPlayer.addEventListener('FinishedLoadingURL', () => SoundPlayer.play())
```
Is that correct?

Unfortunately,I still have a delay about 750ms on iOS when calling `play`. For Android it seems to be fine.

**Comment by johnsonsu** [comment]
Hi @dan-lee, by delay, do you mean the time between the firing of `SoundPlayer.play()` call inside:
```
SoundPlayer.addEventListener('FinishedLoadingURL', () => SoundPlayer.play())
```
and the time music starts playing? Or the delay between `loadUrl` and `SoundPlayer.play()`?

Also, you should probably flip them and do:
```
SoundPlayer.addEventListener('FinishedLoadingURL', () => SoundPlayer.play())
SoundPlayer.loadUrl(url)
```

**Comment by dan-lee** [comment]
Thanks for your reply @johnsonsu!
I mean between calling `SoundPlayer.play()` and the sound actually starting to play on the device. (tested on Simulator and real device.)

Oops, I wrote in the wrong order but I've actually implemented it like you suggested.

**Comment by dan-lee** [comment]
Hey @johnsonsu 

> One hack that might make it a bit better is simply add an artificial delay between calling loadUrl() and telling user that the music is ready, just to give more time for the app to buffer.

That's what I am currently doing. 750ms seems to be the sweet spot.

> I'm already doing prepareToPlay in the native code to minimize the gap between function call and music playing, as suggested on Apple's documentation.

Sounds pretty much like the problem I am facing. Could potentially solve this issue. I'd be happy to test that out, as soon as it's implemented. Thanks for your efforts :)
